version: '3.7'
services:
    predict:
      build: .
      environment:
        - DB_HOST
        - DB_NAME
        - DB_USER
        - DB_CRED
      ports:
        - "${PORT}:3838"
      volumes:
      - /samba/nowcast-data/xsi/data:/root/data
      - /home/rshiny:/root/sql
      restart: always
